---
- hosts: all
  become: yes
  tasks:
    - name: display host name
      command: hostname -f
      register: result
    - name: display result name  
      debug: 
        msg: "{{result}}"
        