---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2 on ubuntu 
    apt:
      name: apache2
      state: present
  - name: start the apache2
    service:
      name: apache2
      state: started