---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"
     
  - name: start the apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"